DOMAIN = "todo_overlay"

DATA_MANAGER = "manager"

WS_TYPE_GET_LIST = "todo_overlay/get_list"
WS_TYPE_MOVE_ITEM = "todo_overlay/move_item"
WS_TYPE_SET_COMPLETED = "todo_overlay/set_completed"
WS_TYPE_RESTORE_COMPLETED = "todo_overlay/restore_completed"
WS_TYPE_CLEAR_COMPLETED = "todo_overlay/clear_completed"
WS_TYPE_SAVE_LIST = "todo_overlay/save_list"
WS_TYPE_LOAD_LIST = "todo_overlay/load_list"
WS_TYPE_LIST_SAVED = "todo_overlay/list_saved"
WS_TYPE_DELETE_SAVED_LIST = "todo_overlay/delete_saved_list"
WS_TYPE_CREATE_ITEM = "todo_overlay/create_item"
WS_TYPE_SET_QUANTITY = "todo_overlay/set_quantity"
WS_TYPE_SET_TAGS = "todo_overlay/set_tags"
WS_TYPE_ADD_TAG = "todo_overlay/add_tag"
WS_TYPE_REMOVE_TAG = "todo_overlay/remove_tag"

SERVICE_SAVE_LIST = "save_list"
SERVICE_LOAD_LIST = "load_list"
SERVICE_DELETE_SAVED_LIST = "delete_saved_list"
SERVICE_ADD_TAG = "add_tag"
SERVICE_REMOVE_TAG = "remove_tag"

ATTR_NAME = "name"
ATTR_PERSIST_STATES = "persist_states"
ATTR_MODE = "mode"
ATTR_ITEM = "item"
ATTR_TAG = "tag"
